### ISSUE TITLE
Add code formatting

### ISSUE THREAD

**Issue by Socolin** [SpecFlowOSS/SpecFlow.Rider#10]

**Comment by nemesv** [comment]
We are currently working on this in the current SpecFlow Team iteration

**Comment by Socolin** [comment]
Here an example how formatting is working from another plugin

https://github.com/JetBrains/resharper-unity/tree/net211/resharper/resharper-unity/src/ShaderLab/Psi/Formatting
https://github.com/JetBrains/resharper-unity/blob/net211/resharper/resharper-unity/src/ShaderLab/Psi/ShaderLabLanguageService.cs#L37

**Comment by nemesv** [comment]
Included in 1.3.7
