### ISSUE TITLE
Daemon stops working due to problems with caches

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#100]
STR:
1. Open https://github.com/SpecFlowOSS/SpecFlow-Examples/tree/master/SpecialChars
2. Build
3. Open https://github.com/SpecFlowOSS/SpecFlow-Examples/blob/master/SpecialChars/SpecialChars/Steps/CheckSteps.cs

ACTUAL: Code analysis is suspended due to exceptions
![image](https://user-images.githubusercontent.com/48007045/117039294-48102900-ad11-11eb-8a01-cd3fa6fd8766.png)

> 14:55:46.907 |E| SpecflowStepsUsagesCache      | :1                 | Failed to determine the kind of step the step Ordmaker starter et spill in <XUnit2.Core>\SpecFlowFeature1.feature.
> --- EXCEPTION #1/1 [LoggerException]
> Message = “Failed to determine the kind of step the step Ordmaker starter et spill in <XUnit2.Core>\SpecFlowFeature1.feature.”
> ExceptionPath = Root
> ClassName = JetBrains.Util.LoggerException
> HResult = COR_E_APPLICATION=80131600
> StackTraceString = “
>   at JetBrains.Util.ILoggerEx.LogMessage[T1,T2](ILogger this, LoggingLevel level, String message, T1 t1, T2 t2)
>      at JetBrains.Util.ILoggerEx.Error[T1,T2](ILogger this, String message, T1 t1, T2 t2)
>      at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsUsages.SpecflowStepsUsagesCache.AddToLocalCache(IPsiSourceFile sourceFile, SpecflowStepsUsagesCacheEntries cacheItems) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Caching\StepsUsages\SpecflowStepsUsagesCache.cs:line 76
>      at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsUsages.SpecflowStepsUsagesCache.Merge(IPsiSourceFile sourceFile, Object builtPart) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Caching\StepsUsages\SpecflowStepsUsagesCache.cs:line 57
>      at JetBrains.ReSharper.Psi.Caches.SimpleICache`1.ProcessDirtyFile(IPsiSourceFile psiSourceFile)
>      at JetBrains.ReSharper.Psi.Caches.SimpleICache`1.ProcessDirty()
>      at JetBrains.ReSharper.Psi.Caches.PsiCaches.<>c__DisplayClass30_0.<Update>b__0()
>      at JetBrains.Util.Logging.LoggerStructuredEx.<>c__DisplayClass9_0.<DoActivity>b__0()
>      at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](Nullable`1 logWithLevel, String key, String message, Func`1 action, Func`2 report)
>      at JetBrains.Util.Logging.LoggerStructuredEx.DoActivity(Nullable`1 logger, String key, String message, Action action)
>      at JetBrains.ReSharper.Psi.Caches.PsiCaches.Update()

Another one

> 16:22:08.875 |E|                               | :1                 | Exception of type 'System.ArgumentOutOfRangeException' was thrown. Parameter name: stepKind Actual value was Unknown.
> --- EXCEPTION #1/2 [ArgumentOutOfRangeException]
> ExceptionPath = Root.InnerException
> ClassName = System.ArgumentOutOfRangeException
> Data.ThreadLocalDebugInfo = “
>   endpoint `MainProtocol.SolutionModel.solutions.[1].altEnterModel.altEnterPopup.$.executeItem` (17651986407494465382)
>    -> property `MainProtocol.SolutionModel.solutions.[1].altEnterModel.altEnterPopupRequested` (15453793485809135084)
>    -> RdDispatcher::FlushAll
> ”
> HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
> Source = ReSharperPlugin.SpecflowRiderPlugin
> ParamName = stepKind
> ActualValue = Unknown
> StackTraceString = “
>   at ReSharperPlugin.SpecflowRiderPlugin.Helpers.SpecflowAttributeHelper.GetAttributeClrName(GherkinStepKind stepKind) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Helpers\SpecflowAttributeHelper.cs:line 33
>      at ReSharperPlugin.SpecflowRiderPlugin.QuickFixes.CreateMissingStep.CreateSpecflowStepFromUsageAction.AddSpecflowStep(IPsiSourceFile targetFile, String classClrName, GherkinStepKind stepKind, String stepText) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\QuickFixes\CreateMissingStep\CreateSpecflowStepFromUsageAction.cs:line 127
>      at ReSharperPlugin.SpecflowRiderPlugin.QuickFixes.CreateMissingStep.CreateSpecflowStepFromUsageAction.<>c__DisplayClass7_0.<OpenFileSelectionModal>b__2(Object e) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\QuickFixes\CreateMissingStep\CreateSpecflowStepFromUsageAction.cs:line 101
>      at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
> > 
[idea.log.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/6422786/idea.log.zip)

**Comment by tkapustina** [comment]
> 19:34:20.949 |E| DaemonThread                  | DaemonThread:62    | One or more errors occurred. Object reference not set to an instance of an object.
> --- EXCEPTION #1/4 [NullReferenceException]
> Message = “Object reference not set to an instance of an object.”
> ExceptionPath = Root.InnerException.InnerException.InnerException
> ClassName = System.NullReferenceException
> HResult = E_POINTER=COR_E_NULLREFERENCE=80004003
> Source = JetBrains.Platform.ProjectModel
> StackTraceString = “
>   at JetBrains.ProjectModel.ProjectFileImpl.<>c.<.cctor>b__72_0(IProjectFile item)
>      at JetBrains.ProjectModel.Impl.CachedProjectItemValue`2.GetValue()
>      at JetBrains.ReSharper.Psi.StandardPsiSourceFilePropertiesProvider.GetPsiProperties(IPsiSourceFileProperties prevProperties, IProject project, IProjectFile projectFile, IPsiSourceFile sourceFile)
>      at JetBrains.ReSharper.Psi.PsiSourceFilePropertiesManager.CalculatePsiSourceFileProperties(IProject project, IProjectFile projectFile, IPsiSourceFile sourceFile)
>      at JetBrains.ReSharper.Psi.PsiSourceFilePropertiesManager.GetPsiProperties(IProject project, IProjectFile projectFile, IPsiSourceFile sourceFile)
>      at JetBrains.ReSharper.Psi.Impl.PsiProjectFile.get_Properties()
>      at JetBrains.ReSharper.Psi.Files.PsiFiles.GetPsiFiles(IPsiSourceFile sourceFile, Type languageType, DocumentRange range, PsiLanguageCategories categories)
>      at JetBrains.ReSharper.Psi.Files.PsiFiles.GetPsiFiles[TLanguage](IPsiSourceFile sourceFile, DocumentRange range, PsiLanguageCategories categories)
>      at JetBrains.ReSharper.Psi.Files.PsiFilesExtensions.GetPsiFile[TLanguageType](IPsiSourceFile sourceFile, DocumentRange range)
>      at ReSharperPlugin.SpecflowRiderPlugin.Daemon.UnresolvedReferenceHighlight.UnresolvedStepHighlightingDaemonStage.<>c.<CreateProcess>b__4_1(IPsiSourceFile x) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Daemon\UnresolvedReferenceHighlight\UnresolvedStepHighlightingDaemonStage.cs:line 44
>      at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
>      at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>      at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>      at JetBrains.Util.CollectionUtil.AsArray[T](IEnumerable`1 enumerable)
>      at JetBrains.ReSharper.Feature.Services.Daemon.DaemonProcessBase.RunStage(IDaemonStage stage, DaemonProcessKind processKind, Action`2 commiter, IContextBoundSettingsStore contextBoundSettingsStore, JetHashSet`1 disabledStages)
>      at JetBrains.ReSharper.Feature.Services.Daemon.DaemonProcessBase.<>c__DisplayClass48_1.<DoHighlighting>g__Stage|2(IDaemonStage stage)
>      at JetBrains.Application.Threading.Tasks.TaskBarrier.<>c__DisplayClass22_1.<EnqueueDependentJobs>b__2()
>      at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
>      at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
>      at System.Threading.Tasks.Task.Execute()

**Comment by Socolin** [comment]
Hi,

The first exception seems to refer to another project

```
14:55:46.907 |E| SpecflowStepsUsagesCache | :1 | Failed to determine the kind of step the step Ordmaker starter et spill in <XUnit2.Core>\SpecFlowFeature1.feature.
--- EXCEPTION #1/1 [LoggerException]
Message = “Failed to determine the kind of step the step Ordmaker starter et spill in <XUnit2.Core>\SpecFlowFeature1.feature.”
```

Do you know what the project it was ? I cannot reproduce the bug with the specified project (https://github.com/SpecFlowOSS/SpecFlow-Examples/tree/master/SpecialChars) and I cannot find the file `SpecFlowFeature1.feature`

**Comment by tkapustina** [comment]
It's unstable to reproduce. Looks like it might be caused by .feature.cs generation

**Comment by tkapustina** [comment]
Attached fresh logs
[log.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/6435569/log.zip)

**Comment by Socolin** [comment]
The last `log.zip` seem empty

After checking the logs again I think I've found something, I'll let you know if I need more details

**Comment by Socolin** [comment]
I tried to find the code where the null referece exception occurs, but I was not able to find this part of the stack in the decompiled code:

```
>   at JetBrains.ProjectModel.ProjectFileImpl.<>c.<.cctor>b__72_0(IProjectFile item)
>      at JetBrains.ProjectModel.Impl.CachedProjectItemValue`2.GetValue()
```

But from what I understand `IProjectFile item` is null, but in the whole stack I cannot find a way for this to happen, so I'm a little confuse and I don't know how reproduce or how to fix this

**Comment by tkapustina** [comment]
STR:
1. Unload all projects
2. Reload all projects
3. Open a cs file
[TestProject4.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/6509044/TestProject4.zip)

**Comment by SirDuke** [comment]
@Socolin this code in UnresolvedStepHighlightingDaemonStage.CreateProcess looks suspicous for me:
`
return _specflowStepsUsagesCache.StepUsages.SelectMany(x =&gt; x.Value.Keys).Distinct()                    .Select(x =&gt; x.GetPsiFile&lt;GherkinLanguage&gt;(x.Document.GetDocumentRange()))                    .Select(file =&gt; new UnresolvedStepsHighlightingDaemonStageProcess(process, (GherkinFile) file, _registrar));
`

Is there a guarantee that x.Value.Keys contains only valid files? Probably, need to add filter for IsValid:
>Where (x => x.IsValid())

**Comment by Socolin** [comment]
I tried the fixed proposed by @SirDuke 

Can you try if this build fix the issue

https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/878511242 ?

**Comment by tkapustina** [comment]
I cannot install it for some reasons. Could it be incompatible with 2021.1.3?
![image](https://user-images.githubusercontent.com/48007045/119827445-d0917c00-bf01-11eb-8a92-4fa9907d098b.png)

**Comment by nemesv** [comment]
The github build puts at plugin into an extra zip. 
You should first unzip this SpecFlowPlugin.zip which should contain a another zip named:  specflowriderplugin-1.6.0.zip. 
This is the actual plugin package what you should be able to install to 2021.1.3

**Comment by tkapustina** [comment]
Ah, I see, osx unpacks the second zip too by default. That's why I had not seen any zip files. Thanks

**Comment by tkapustina** [comment]
Verified. Seems to be working.
