### ISSUE TITLE
Support move to folder refactoring for feature files

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#104]
STR1:
1. Select a feature file with the nested cs file
2. Invoke Refactor This -Move to folder
3. Apply refactoring

ACTUAL:
csproj is not updated, build fails
`  Source file 'C:\Users\Tatiana.Kapustina\RiderProjects\SpecFlow.Example.AllTestRunners\MSTest.Net5\SpecFlowFeature1.feature.cs' could not be found.`

**Comment by nemesv** [comment]
This is caused by bug in Rider: https://youtrack.jetbrains.com/issue/RIDER-63340

**Comment by tkapustina** [comment]
Filed another issue regarding the run gutter marks in Rider, [RIDER-63895](https://youtrack.jetbrains.com/issue/RIDER-63895)
