### ISSUE TITLE
Add icons for feature files to 'find usages' dropdown

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#105]
STR:
1. Open a definition file
2. Invoke find usages on a method

ACTUAL:
![image](https://user-images.githubusercontent.com/48007045/118848132-25683d80-b8d7-11eb-990d-ccd865302dd7.png)

EXPECTED: It would be nice to have specflow icons here

**Comment by Socolin** [comment]
See https://jetbrains.slack.com/archives/CBZ36NH7C/p1622033083008100 for a solution on how to fix this
