### ISSUE TITLE
More convenient way of packing SpecFlow on GitHub Actions

### ISSUE THREAD

**Issue by ForNeVeR** [SpecFlowOSS/SpecFlow.Rider#114]
As of now, the plugin is packed on GitHub Actions properly, but somewhat inconvenient for the users who install it from GitHub. E.g. [see this build](https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/878511242).

The following archive structure is created:
```
SpecFlow.zip
- specflowriderplugin-1.6.0.zip
-- ** plugin files are here
```

So, to actually install the plugin, the user has to download the top-level archive, extract the second-level archive from it, and then install `specflowriderplugin-1.6.0.zip` into the IDE.

In certain situations, e.g. on macOS (surprisingly), the nested archive gets unpacked automatically, so the user is unaware that the second archive even existed, and is unable to install the plugin.

You may pack the plugin specially for it to be downloadable from GitHub, as I do with the AvaloniaRider plugin.

[Here's the example](https://github.com/ForNeVeR/AvaloniaRider/blob/e0378290cdfa53d94f8d5f30bdb8acaf2ff34fe5/.github/workflows/main.yml#L60-L69). It will prepare a single archive to be downloadable from GitHub, specifically for easy installation.

**Comment by Socolin** [comment]
Thanks, I was waiting for https://github.com/actions/upload-artifact/issues/39, for some reason this seems to be a problem on all pipeline I tested so far :( 
Since you already wrote the workaround I'm going to add as soon as I find some time to do so.

**Comment by Socolin** [comment]
It's now fixed.
