### ISSUE TITLE
Upgrade to 2021.2

### ISSUE THREAD

**Issue by Socolin** [SpecFlowOSS/SpecFlow.Rider#119]
EAP is now available we should be able to start a branch to prepare the new version.

There is a breaking change that was announce in slack 

https://jetbrains.slack.com/archives/CBZ36NH7C/p1619416162142100

**Comment by mariostnr** [comment]
shipped - the latest version can be found here: https://plugins.jetbrains.com/plugin/15957-specflow-for-rider/versions
