### ISSUE TITLE
When double-clicking a test in the Test Runner, open the Feature file instead of the generated C#

### ISSUE THREAD

**Issue by dfruhling** [SpecFlowOSS/SpecFlow.Rider#128]
When I double-click a test in the "Unit Tests" window, I expect to be taken to the file from which I can review that test and then rerun it (aka the `.feature` file). However, double-clicking the test name ends up taking me to SpecFlow's generated `.feature.cs` file. This is not helpful because it is not what the user is meant to read/review.

**Comment by nemesv** [comment]
We already have an issue for this here: #37. Currently it is not supported by Rider.

**Comment by dfruhling** [comment]
Gotcha -- thanks for responding so quickly!
