### ISSUE TITLE
Run gutter mark appears for scenarios without title

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#136]
STR:
1. Open a feature file (net48)
2. Add a scenario without the title

ACTUAL:
![image](https://user-images.githubusercontent.com/48007045/121345760-ee150b80-c92d-11eb-97d5-7e9e6d3bc810.png)
![image](https://user-images.githubusercontent.com/48007045/121345917-1ac92300-c92e-11eb-99cc-0fd7b06ce532.png)

EXPECTED: 
An error message should be displayed in the editor

**Comment by nemesv** [comment]
Fixed in version 1.8.0. The gutter mark is no longer shown for untitled scenarios.

**Comment by tkapustina** [comment]
verified
