### ISSUE TITLE
Specflow plugin isn't enabled properly in 2021.2

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#144]
STR:
1. Install Specflow plugin
2. Open feature file

ACTUAL: The plugin doesn't ask for restart and behaves like a dynamic plugin but the feature set is not actually enabled until restart. 
![image](https://user-images.githubusercontent.com/48007045/122551651-f3650b00-d03d-11eb-8f03-26b9bebac1b1.png)

EXPECTED: It shouldn't be dynamic or has to be fully implemented as a dynamic one.

**Comment by nemesv** [comment]
Which Rider build you are using? It seems this is a new problem with 2021.2.x.

**Comment by tkapustina** [comment]
This is Rider 2021.2 as the plugin will be featured in it so this is my first priority to test.

**Comment by nemesv** [comment]
The restart required flag was missing from the plugin. Can you try out new with this new version: https://github.com/SpecFlowOSS/SpecFlow.Rider/suites/3043671083/artifacts/69129019?

**Comment by nemesv** [comment]
Fixed in 1.9.1

**Comment by tkapustina** [comment]
verified in 1.9.1
