### ISSUE TITLE
Add support for case insensitive code completion

### ISSUE THREAD

**Issue by nemesv** [SpecFlowOSS/SpecFlow.Rider#148]
From https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/86#issuecomment-881491556

Rider has a special setting for this, please, check File | Settings | Editor | General | Code Completion - Match case option.

**Comment by nemesv** [comment]
@tkapustina Implemented in version 1.9.2

**Comment by tkapustina** [comment]
Yay! Thank you!

**Comment by tkapustina** [comment]
Hi Viktor!
I don't really get how it's implemented. Could you please attach a video?

**Comment by nemesv** [comment]
We have two kind of code completion, one for the Gherkin keywords (Feature, Scenario, Given, When, etc.) and one for the step difinitions.

The Step complication always need sto be case sensitive otherwise it can cause problems when executing the steps.

Previously the Keyword completion was always case sensitive and it was not configurable through Settings > Editor > Code Completion > Match Case

Now in version 1.9.2. the Keyword completion is case insensitive by default: so you can type a lowercase 't' to get the 'Then'

![then1](https://user-images.githubusercontent.com/251330/127484296-8c930d08-d63f-4a35-ae92-ca4c5e9326e2.gif)

But the use when user turns on the Match case: First letter only, it will only work with capital 'T'

![then2](https://user-images.githubusercontent.com/251330/127484397-d9bc02f0-f2e2-4111-a954-b7c0a706260f.gif)

**Comment by tkapustina** [comment]
Ah I was thinking about the step completion. Thank you very much!

**Comment by Socolin** [comment]
@tkapustina @nemesv Can we close this ? or is there still things to do ?
