### ISSUE TITLE
Ability to fold Feature/Scenario/Background

### ISSUE THREAD

**Issue by Socolin** [SpecFlowOSS/SpecFlow.Rider#15]
In order to provide better readability for large feature files
for Developers and Testers
the Rider plugin will allow collapsing/expanding feature file sections based on Gherkin keywords

whereas currently there is no collapse/expand functionality available

Personas:

- Developers
- Testers

Should recognize folding based on keyword
- should be able to fold Scenarios
- should be able to fold Example groups
- should be able to fold backgrounds
- should be able to fold rule keyword

Rider Documentation should be extended

**Comment by nemesv** [comment]
Included in version 1.4.0
