### ISSUE TITLE
Navigation to steps doesn't work when stepAssembly used in SpecFlow 2.2.1

### ISSUE THREAD

**Issue by Roganik** [SpecFlowOSS/SpecFlow.Rider#151]
Hi

We're using the SpecFlow 2.2.1 and have a separate project with Specs. And navigation to the step definition doesn't work.
The steps are defined in multiple other assemblies. (App.config -> specFlow node -> stepAssemblies node).

It's hard to figure out what causes 'Navigation doesn't work'. 

Do you expect navigation to work for v2.2.1? (i didn't found the list of supported versions)

If it should work, can you please advise are there any logs in Rider or somewhere else I can look at to investigate further?

Thanks!

**Comment by SabotageAndi** [comment]
We generally support only the latest version of SpecFlow in our tools. 
Between 2.* and 3.* were a lot of changes and we sure didn't test it with this old versions.

What is the reason that you are using such an old SpecFlow version?
