### ISSUE TITLE
go to step definition works in the IDE, complains can't find matching step definition when running the test

### ISSUE THREAD

**Issue by ardz** [SpecFlowOSS/SpecFlow.Rider#152]
.net 5.0 project, latest version of specflow for rider

pressing F12 on the step reveals the expected step method as expected but running the test fails

I've tried regenerating the bindings

The step assembly is located in a separate class library 

this has been specified in the specflow.json file in the test project

any assistance would be massively appreciated

**Comment by Socolin** [comment]
Hello,

Can you give us the step definition attribute (in `.cs`) and the step as you use it (in `.feature`) and the `specflow.json` ? (I think the plugin ignore the assembly configure in the specflow`.json` and resolve steps as long as the project is referenced, you may want to check for a typo in this file too.)

Also can you try to delete all `.feature.cs` then build again, SpecFlow is generating `.feature.cs` automatically now.

**Comment by ardz** [comment]
Tried the above - didn't help unfortunately. Specflow is doing the same thing in Visual Studio too - this has been an issue with specflow for as long as I can remember now. It worked briefly for a while when I used in a dot net framework project years ago.

**Comment by Socolin** [comment]
In this case I think you should open an issue on the SpecFlow project https://github.com/SpecFlowOSS/SpecFlow

Also adding a mini repro project helps a lot to understand the problem. If you can find few minutes to make one it would help.

Can I close this issue ?

**Comment by Socolin** [comment]
I'm closing since the issue seems to be on Specflow, and not in the plugin
