### ISSUE TITLE
Tests fail to re-load after changing build configuration

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#154]
STR:
1. Create a specflow project
2. Build
3. Change the solution config from Debug to Release
![image](https://user-images.githubusercontent.com/48007045/133224194-7b184a4b-1b57-428c-b30b-406308d0cc3b.png)
4. Check the UT explorer

ACTUAL: The UT explorer is empty. Please, see the initial report, https://youtrack.jetbrains.com/issue/RIDER-67527

**Comment by alimogithub** [comment]
@craigwardman @tkapustina thanks for raising this, we will look into it

**Comment by Socolin** [comment]
Hello, I cannot reproduce.

Can you check if this is fixed or provide a repro ?

**Comment by craigwardman** [comment]
> Hello, I cannot reproduce.
> 
> Can you check if this is fixed or provide a repro ?

Pretty sure this was fixed a while ago.
