### ISSUE TITLE
Error when building test project: Could not find a part of the path 'SomeProject/**/*.feature

### ISSUE THREAD

**Issue by sroosen** [SpecFlowOSS/SpecFlow.Rider#157]
When my test project has finished building it adds a ** *.feature item to my project and I get the following error message:
Could not find a part of the path '/Users/stijn/Sources/mycompany/someproject/someproject.Domain.Tests/**/*.feature'

<img width="467" alt="Schermafbeelding 2021-10-06 om 21 05 09" src="https://user-images.githubusercontent.com/124242/136267016-06c67050-8b9e-420b-a266-5842ef5e7332.png">

  Generation error: Message: Could not find a part of the path '/Users/stijn/Sources/mycompany/someproject/someproject.Domain.Tests/**/*.feature'.
AppDomain Information: 
	Name: MSBuild
	BaseDirectory: /usr/local/share/dotnet/sdk/3.1.412/
Loaded Assemblies:
Fullname | Location
BoDi, Version=1.5.0.0, Culture=neutral, PublicKeyToken=ff7cd5ea2744b496 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/BoDi.dll
Gherkin, Version=19.0.3.0, Culture=neutral, PublicKeyToken=86496cfa5b4a5851 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/Gherkin.dll
JetBrains.Lifetimes, Version=777.0.0.0, Culture=neutral, PublicKeyToken=3c74c1a6a8683340 | /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.Lifetimes.dll
JetBrains.Platform.MsBuildTask, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325 | /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.Platform.MsBuildTask.dll
JetBrains.RdFramework, Version=777.0.0.0, Culture=neutral, PublicKeyToken=3c74c1a6a8683340 | /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.RdFramework.dll
Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/sdk/3.1.412/Microsoft.Build.dll
Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/sdk/3.1.412/Microsoft.Build.Framework.dll
Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/sdk/3.1.412/Microsoft.Build.Tasks.Core.dll
Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/sdk/3.1.412/Microsoft.Build.Utilities.Core.dll
Microsoft.DotNet.PlatformAbstractions, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/Microsoft.DotNet.PlatformAbstractions.dll
Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/Microsoft.Extensions.DependencyModel.dll
Microsoft.NET.Build.Tasks, Version=3.1.4.36309, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/Sdks/Microsoft.NET.Sdk/tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll
Microsoft.Win32.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/Microsoft.Win32.Primitives.dll
MSBuild, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/sdk/3.1.412/MSBuild.dll
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/mscorlib.dll
netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/netstandard.dll
NuGet.Build.Tasks, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/NuGet.Build.Tasks.dll
NuGet.Commands, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/NuGet.Commands.dll
NuGet.Common, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/NuGet.Common.dll
NuGet.Frameworks, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/NuGet.Frameworks.dll
NuGet.ProjectModel, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | /usr/local/share/dotnet/sdk/3.1.412/NuGet.ProjectModel.dll
SpecFlow.Internal.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/SpecFlow.Internal.Json.dll
SpecFlow.Tools.MsBuild.Generation, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/SpecFlow.Tools.MsBuild.Generation.dll
System.AppContext, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.AppContext.dll
System.Buffers, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Buffers.dll
System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/System.CodeDom.dll
System.Collections, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.dll
System.Collections.Concurrent, Version=4.0.15.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Concurrent.dll
System.Collections.Immutable, Version=1.2.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Immutable.dll
System.Collections.NonGeneric, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.NonGeneric.dll
System.Collections.Specialized, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Collections.Specialized.dll
System.ComponentModel.Primitives, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ComponentModel.TypeConverter.dll
System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/System.Configuration.ConfigurationManager.dll
System.Console, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Console.dll
System.Diagnostics.FileVersionInfo, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.Process.dll
System.Diagnostics.Tracing, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Diagnostics.Tracing.dll
System.Drawing.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Drawing.Primitives.dll
System.IO, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.IO.dll
System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.IO.FileSystem.dll
System.IO.MemoryMappedFiles, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.IO.MemoryMappedFiles.dll
System.IO.Pipes, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.IO.Pipes.dll
System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Linq.dll
System.Memory, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Memory.dll
System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Net.Http.dll
System.Net.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Net.Primitives.dll
System.Net.Sockets, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Net.Sockets.dll
System.ObjectModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.ObjectModel.dll
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.CoreLib.dll
System.Private.Uri, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.Uri.dll
System.Private.Xml, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Private.Xml.dll
System.Reflection, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.dll
System.Reflection.Emit.ILGeneration, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.Emit.Lightweight.dll
System.Reflection.Metadata, Version=1.4.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.Metadata.dll
System.Reflection.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Reflection.Primitives.dll
System.Resources.ResourceManager, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Resources.ResourceManager.dll
System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.dll
System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Extensions.dll
System.Runtime.InteropServices, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.Loader, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Loader.dll
System.Runtime.Serialization.Formatters, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Primitives, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Runtime.Serialization.Primitives.dll
System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Security.Cryptography.Primitives.dll
System.Text.Encoding.CodePages, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Text.Encoding.CodePages.dll
System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Text.Encoding.Extensions.dll
System.Text.RegularExpressions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Text.RegularExpressions.dll
System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.dll
System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Tasks.dll
System.Threading.Tasks.Dataflow, Version=4.6.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.Parallel, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Tasks.Parallel.dll
System.Threading.Thread, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.Thread.dll
System.Threading.ThreadPool, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Threading.ThreadPool.dll
System.Xml.ReaderWriter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/System.Xml.ReaderWriter.dll
TechTalk.SpecFlow, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/TechTalk.SpecFlow.dll
TechTalk.SpecFlow.Generator, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/TechTalk.SpecFlow.Generator.dll
TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.nunit/3.9.22/build/netcoreapp2.1/TechTalk.SpecFlow.NUnit.Generator.SpecFlowPlugin.dll
TechTalk.SpecFlow.Parser, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/TechTalk.SpecFlow.Parser.dll
TechTalk.SpecFlow.Utils, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | /Users/stijn/.nuget/packages/specflow.tools.msbuild.generation/3.9.22/tasks/netcoreapp2.1/TechTalk.SpecFlow.Utils.dll
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/stijn/Sources/mycompany/someproject/someproject.Domain.Tests/**/*.feature'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at TechTalk.SpecFlow.Generator.FeatureFileInputExtensions.GetFeatureFileContentReader(FeatureFileInput featureFileInput, ProjectSettings projectSettings)
   at TechTalk.SpecFlow.Generator.TestGenerator.GenerateTestFileCode(FeatureFileInput featureFileInput)
   at TechTalk.SpecFlow.Generator.TestGenerator.GetGeneratedTestCode(FeatureFileInput featureFileInput)
   at TechTalk.SpecFlow.Generator.TestGenerator.GenerateTestFileWithExceptions(FeatureFileInput featureFileInput, GenerationSettings settings)
   at TechTalk.SpecFlow.Generator.ErrorHandlingTestGenerator.GenerateTestFile(FeatureFileInput featureFileInput, GenerationSettings settings)

**Comment by rfaes** [comment]
I am having the same issue.
Specflow versions:
    <PackageReference Include="SpecFlow" Version="3.9.40" />
    <PackageReference Include="SpecFlow.MsTest" Version="3.9.40" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.40" />

Used is .Net5.0

**Comment by Socolin** [comment]
I'm closing this since it's not related to the plugin, please open an issue on Specflow tracker https://github.com/SpecFlowOSS/SpecFlow/issues
