### ISSUE TITLE
Not compatible with the version of your running IDE (Rider 2022.1 EAP 6)

### ISSUE THREAD

**Issue by molszews** [SpecFlowOSS/SpecFlow.Rider#167]
Do you plan to support Rider 2022 EAP?
Current version (1.10.0) is incompatible as it requires IDE build 213.* or earlier

**Comment by SabotageAndi** [comment]
We always try to support the latest version of Rider. @Socolin is working on getting it to work on the EAP, but there are problems where he needs the help from JetBrains.

**Comment by Socolin** [comment]
Hello,

A version is available here https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/2028576256

Or it should be available directly in Rider, in a day or 2 once jetbrains reviewed the new version.

**Comment by tkapustina** [comment]
1.11 version doesn't work with Rider 2022.1: no project templates, no code analysis

**Comment by AlexanderDorofeev** [comment]
Same for me. Updated to Rider 2022.1 which was released recently and specflow 1.11 is broken there

**Comment by SabotageAndi** [comment]
We are working on fixing it.

**Comment by gastonmuijtjens** [comment]
Same issue, upgraded to Rider 2022.1 and the SpecFlow plugin is no longer working properly for me

**Comment by SabotageAndi** [comment]
I just uploaded a fixed version to the JetBrains Marketplace. The approval needs about 2 business days and it should be then available. 

For the people who are interested in which changes were needed to fix this, have a look at this diff: https://github.com/SpecFlowOSS/SpecFlow.Rider/compare/097d914235c1d82ded76856802fe8668f566b90c..a19f912b43631cb62606fbff1dad9ac4b938cbe6

There are always changes in the build system and the API, so it is way more than updating some packages.
