### ISSUE TITLE
Specflow 'Go To Declaration or Usage' feature file navigates to the wrong step definition

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#178]
Initial request: https://youtrack.jetbrains.com/issue/RIDER-78256/Specflow-Go-To-Declaration-or-Usage-feature-file-navigates-to-the-wrong-step-definition

In the feature file we have a step called 'I have an existing document <document> in the Command Api'. And it should navigate to the '[Given(@"I have an existing document (.*) in the Command Api")]' step definition, but it leads to '[Given(@"I have an existing document (.*)")]'. These both steps have the identical first part of sentence but the different end.In compare with Visual Studio 2022 - there it works well.

Version: 2022.1.1Build: RD-221.5591.20Timezone: Europe/PragueEvaluation: trueEnvironment: RD-221.5591.20, JRE 11.0.14.1 1-b2043.45x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1920.0x1080.0, 1920.0x1080.0.NET Framework 4.0.30319.42000

**Comment by barisgul** [comment]
Hello, 
I am facing with the same problem. It works on Visual studio 2022 but doesn't work in Rider 2022.3.1
Is there any plan to fix it?

**Comment by Socolin** [comment]
> Hello, I am facing with the same problem. It works on Visual studio 2022 but doesn't work with Rider 2022.3.1 I think Scope binding is not working properly. Because I have Scope attribute in my step definition class and it implements another class. Here is the example:
> 
> * OS: Windows
> * Rider version: 2022.3.1
> * Specflow plugin version: 1.15.3
> 
> **1. Scenario:** ![image](https://user-images.githubusercontent.com/4164016/213694157-38cefd72-9859-4a1c-8de3-c84b3256780e.png)
> 
> **2. Scope Binding in GetPersonStepDefinitions.cs** ![image](https://user-images.githubusercontent.com/4164016/213681633-50789ab2-0b91-4c8c-938f-9533489aeded.png)
> 
> **3. The step I'm expecting to bind in GetPersonStepDefinitions.cs** ![image](https://user-images.githubusercontent.com/4164016/213694223-e1065da4-5b49-4aa4-9a93-f46519d00b72.png)
> 
> **4. Actual binding in completely a different class (DuplicationCheckStepDefinitions.cs)** ![image](https://user-images.githubusercontent.com/4164016/213682184-0ab52d91-2871-442e-987f-d1c10c2cf528.png) ![image](https://user-images.githubusercontent.com/4164016/213682354-f1de7f8c-c28b-4319-994f-0fdea324d849.png)
> 
> Is there any plan to fix it?

Yes, when I can find some time to do it

**Comment by Jazzman82** [comment]
We have the same issue here.

**Comment by aventus13** [comment]
I have the same issue. Trying to navigate to a step definition seems to be randomly picking definitions, even though they are supposed to be scoped to another feature. This is especially frustrating when I create a new feature, write up a number of steps, and expect that the IDE will pick up that no matching definitions were found, thus suggesting to create them for me. Unfortunately, it seems to be finding some other scoped steps and considers them to be valid for the new feature.

**Comment by Socolin** [comment]
This should be fixed in the next version.

Can you check this when it's available (1.21) or by downloading it here https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/7001534208 (Work with latest 2023.3 EAP) and let me know if this fix your issue ?

**Comment by Jazzman82** [comment]
This issue is fixed here.
