### ISSUE TITLE
Unit test explorer opens code behind file

### ISSUE THREAD

**Issue by MeijerM1** [SpecFlowOSS/SpecFlow.Rider#181]
**Explanation**
The `Jump to source` option in the unit test explorer tab opens the generated code behind file instead of navigating to the actual scenario in the feature file. It would be much more useful if this navigated to the feature file.

I've done some additional testing and have found the following behaviour:
When a test case has failed the jump to source option will navigate to the actual feature file. If the test case has passed the jump to source option will navigate to the code behind file.

**Specflow plugin version**
1.14.2

**Rider version**
2022.2.2

**OS version**
Windows 10.0.19044 Build 19044

**Comment by Socolin** [comment]
Duplicate https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/37
