### ISSUE TITLE
Support for Rider 2022.3 EAP

### ISSUE THREAD

**Issue by kzryzstof** [SpecFlowOSS/SpecFlow.Rider#183]
The EAP versions of Rider are out. It would be great to bump the versions in the following files:

**gradle.properties**
ProductVersion=2022.3-EAP1-SNAPSHOT

**Plugins.prop**
<SdkVersion>2022.3.0-EAP01</SdkVersion>

**Comment by Otiel** [comment]
Seems that version 1.15.0 [released](https://plugins.jetbrains.com/plugin/15957-specflow-for-rider/versions/stable/252317) is compatible with Rider 2022.3.

**Comment by Constante-ou-Mort** [comment]
![image](https://user-images.githubusercontent.com/48734766/203528399-64bae924-a5b4-4d0c-b9a0-25fa4371ebfe.png)
the problem is still here

**Comment by kzryzstof** [comment]
It does not look like it is :(

![Screenshot 2022-11-23 at 7 28 00 AM](https://user-images.githubusercontent.com/38137839/203547045-659f7f97-1445-4790-94d0-9d19d8f45bec.png)

**Comment by Socolin** [comment]
Should be compatible with next EAP, I used -SNAPSHOT version instead of EAP.

**Comment by Socolin** [comment]
I republished a version that should work this time, you can already download it here https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/3560095648
