### ISSUE TITLE
Fix comments indentation when running "reformat and cleanup"

### ISSUE THREAD

**Issue by Otiel** [SpecFlowOSS/SpecFlow.Rider#185]
When cleaning a `.feature` file, all comments indentation is removed. For instance, this is my code:

![image](https://user-images.githubusercontent.com/3851902/202454141-6596b139-1177-4fd2-9a1e-ce595e5bd67d.png)

After running "reformat and cleanup", all comments get pushed to the left:

![image](https://user-images.githubusercontent.com/3851902/202454272-9a3f39a1-df2b-4b99-a277-82c3baad2e8a.png)

This makes `.feature` files hard to read when they're composed of multiple `Scenario`.

It would be great if comments indentation were modified to match the next step indentation, or at worse, left as they are when running "reformat and cleanup".

**Comment by Socolin** [comment]
Should be fixed in 1.23.
Can you check if this fix you problem ?

The version is available here today, and in a few day in the marketplace:
https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/7043312543 on 2023.3 RC

**Comment by Otiel** [comment]
Yes, I confirm this is fixed in 1.23.

Thanks a lot! ❤️
