### ISSUE TITLE
Table Columns are not Aligning with the latest Rider Plugin Version on 2022.3 EAP 

### ISSUE THREAD

**Issue by alfkonee** [SpecFlowOSS/SpecFlow.Rider#187]
![Specflow Error](https://user-images.githubusercontent.com/3909521/206009604-fb01b0ec-3f66-4c19-961c-88b7ecfa05e9.gif)
As Shown above the Specflow Plugin is no automatically aligning the Tables anymore on Rider Version 2022.3 EAP 9

This was working in the 2022 versions

**Comment by Socolin** [comment]
This is related to a changes in Rider. This was fixed (I was able to test a build with the fix) but the fix was not release yet, maybe for 2022.3.0 for sure 2022.3.1

**Comment by MeijerM1** [comment]
Any change this will be released as a 'hotfix' of some sort?

This is quite an annoying bug which messes up the formatting of all of our feature files.

**Comment by radu-v** [comment]
if there would be an option to disable the formatting offered by the plugin (or just skip formatting the tables), that would be a good workaround

**Comment by Socolin** [comment]
Fix should be when rider release 2022.3.1

**Comment by JorisVanEijden** [comment]
2022.3.1 is released and the issue is fixed.
