### ISSUE TITLE
Double click on successful scenario navigates to generated feature C# class

### ISSUE THREAD

**Issue by pmihalcin** [SpecFlowOSS/SpecFlow.Rider#188]
When I double click on **failed** scenario run in Unit Tests pane, Rider navigates me to the that scenario inside feature file.
When I double click on **successful** scenario run in Unit Tests pane, Rider navigates me to the method inside generated feature C# class.

Can you fix this so it **always** navigates to the scenario inside feature file?

**Comment by Socolin** [comment]
Duplicate https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/37
