### ISSUE TITLE
Create step definition in partial class (in separate file) of selected class

### ISSUE THREAD

**Issue by Andras-Csanyi** [SpecFlowOSS/SpecFlow.Rider#19]
## Motivation
My usage pattern for dealing with step definitions is that I put every definition a [separate partial classes](https://github.com/Andras-csanyi/DigitalLibrary/tree/master/src/MasterData/MasterData.BusinessLogic.Features/StepDefinitions). This way I have small and easy to manage code in each partial classes, my ultimate goal always that the code shouldn't be longer than my screen. The other result of managing stepdefinitions is having lot of files.
 
The `Create Step` functionality puts the generated step definition into a class. If I follow my pattern than the next step for me is always 1, put the cursor in the method name 2, Refactor - Partial class, 3, Add method name and click. It is not the end of the world but I rather have Rider working instead of me.

## Suggestion
When there is a not bound step definition then display another option below `Create Step`, called `Create Step in partial class of [selected class]`. Then Rider
- makes class partial if it is not already partial
- adds a partial class to it in a separate file
- filename is the same as the newly created method name

## Example
- user selects `Create Step in partial class of [selected class]`
- user selects `StepDefinitions.cs`
- Rider makes `StepDefinitions.cs` partial if it is not partial
- Rider creates `ThisStepIsNotBoundYet.cs`
- Rider creates `class partial StepDefinitions` in `ThisStepIsNotBoundYet.cs` file
- Rider adds `ThisStepIsNotBoundYet()` method to partial class in `ThisStepIsNotBoundYet.cs` file

```gherkin
Scenario: a nice example
    Given this step is not bound yet
```

```c#
// filename: StepDefinitions.cs
namespace StepDefinitions {

    public partial class SomethingStepDefs {
        // already implemented stuff
    }

}
```

```c#
// filename: ThisStepIsNotBoundYet.cs
namespace StepDefinitions {

    public partial class SomethingStepDefs {
        [Given(@"this step is not bound yet")]
        public void ThisStepIsNotBoundYet() {}
    }

}
```

**Comment by nemesv** [comment]
Fixed in version 1.7.0
