### ISSUE TITLE
There is no option available to disable the formatting of Gherkin tags.

### ISSUE THREAD

**Issue by BondarenkoDmytro** [SpecFlowOSS/SpecFlow.Rider#197]
Hey,

during the setting of Code Style rules on the project I faced an issue with the formatting of Gherking tags.

I'm using [SpecFlow for Rider](https://plugins.jetbrains.com/plugin/15957-specflow-for-rider) plugin as we use C# + SpecFlow on the project.

I'd like to have them placed in one line, but after applying Reformat Code tags are placed in a column, one under the other. It doesn't suit me, I'd like to keep them in one line after applying Reformat Code.

I didn't find any option in Code Style setting to disable it and keep them in one line. I will be nice to have an option to disable the formatting of tags.

### Plugin version: 1.16.1

![image](https://user-images.githubusercontent.com/112479410/236436694-9aa85e39-ca19-441f-aa1a-bb4c7b75c0cc.png)

![image](https://user-images.githubusercontent.com/112479410/236436791-9fad902e-2595-4b47-978d-1e6773fa1d2b.png)

**Comment by Socolin** [comment]
Will be available in next version in Code style settings
![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/539620/81413559-3d20-46aa-be41-5c423ee10fb0)
