### ISSUE TITLE
Feat: Support place breakpoint from specflow file

### ISSUE THREAD

**Issue by Socolin** [SpecFlowOSS/SpecFlow.Rider#2]
Place a breakpoint should allow to during scenario

_Step into_ should go to the step declaration
_Step over_ should go to the next step

**Comment by kotelni** [comment]
It is really a basic feature, needed often. If you have a step which is called multiple times with different parameters from the same feature file, then you cannot really put a breakpoint in the step itself (in C#), because it will be called from multiple places of the feature file.

**Comment by Socolin** [comment]
A first version is available here, but I need to figure out why the lines highlighted during debug are bigger than the steps

https://github.com/SpecFlowOSS/SpecFlow.Rider/tree/breakpoint-featurefile

![BugDebugHighlightTooLarge](https://user-images.githubusercontent.com/539620/111423874-4ccc3f80-86c7-11eb-9cd7-fb72a9162315.gif)

**Comment by nemesv** [comment]
Included in version 1.4.0

**Comment by kotelni** [comment]
Yes, a breakpoint can now be placed and the debugger will stop there. BUT the next logical step for the developer is to step-into the line (F11). This does not work properly. It either goes to the auxiliary classes (not interesting to anybody, like StepRunner), or if the Setting is "Enable External Code Debug" is off, it does not go into at all, i.e. goes to the next line on the feature file (as if I pressed F10).

It should go directly to the bound method in .cs file with steps implementation.

**Comment by Socolin** [comment]
Hello,

We don't have control over the debugger part so it's a bit tricky, so far it's possible to achieve this with one more click on this icon:
![image](https://user-images.githubusercontent.com/539620/115492265-7977f780-a22f-11eb-926c-d074f88a07e0.png)

- Place a breakpoint on the steps
- When the breakpoint trigger, use "Go to declaration" shortcut, then click the button

Here an example:

![ExampleDebugerGoToStep](https://user-images.githubusercontent.com/539620/115492398-be039300-a22f-11eb-939d-5b073652eac7.gif)

If you think this is not good enough, please open another issue to track this, and I'll ask to the jetbrains team if it would be possible to hooks the "Step into"  or find another workaround :)

**Comment by kotelni** [comment]
Thanks, Socolin for suggested workaround. I will try and see if it is good enough.
