### ISSUE TITLE
When user write {string} then Rider not understand but Visual Studio can

### ISSUE THREAD

**Issue by supertgtline** [SpecFlowOSS/SpecFlow.Rider#200]
Example: 
[When(@"user tries to login with ""(.*)"" and ""(.*)""")] Can understand by Rider
[When(@"user tries to login with ""{string}"" and ""(.*)""")] Can't understand by Rider

**Comment by ajeckmans** [comment]
This has to do with the known limitations: https://github.com/SpecFlowOSS/SpecFlow.Rider#limitations
See also https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/184 Adding support for Cucumber Expression

**Comment by Socolin** [comment]
I'll close this as duplicate
