### ISSUE TITLE
Feature file formatting not working as expected on Rider 2022.3

### ISSUE THREAD

**Issue by ImadMAKS** [SpecFlowOSS/SpecFlow.Rider#201]
When reformatting a feature file, I am expecting all the columns to line up. However, the current behavior is different; the reformatting only adds one space before and one space after the text.

See the following gif:
![Screen Recording 2023-07-07 at 9 50 25 AM](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/122645670/da38a901-7f0d-4bf3-bb2b-b835717b9541)

As shown in the attached gif, when I hit reformat, the result is not what is expected. The expected result should look like the following:

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/122645670/f6e5a654-c483-402a-ab0c-cd875c0c500b)

Cheers

**Comment by Socolin** [comment]
What version are you using ? Have you tried on 2023.2-EAP7 ?

**Comment by ImadMAKS** [comment]
I was using version 2022.3.3.
I have just switched to 2023.2-EAP7, and it works fine.
Thank you!
