### ISSUE TITLE
Support for Rider 2023.3

### ISSUE THREAD

**Issue by jasttrifork** [SpecFlowOSS/SpecFlow.Rider#204]
With a new Rider release around the corner it would be nice to make sure that support for the SpecFlow plugin will follow.

Currently the plugin has a limit of build version `232.*`, where the new release will be build `233.*`.
![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/137154007/3949b1f5-ceae-479d-bbd7-4e0ad74e6da1)

**Comment by Socolin** [comment]
I will try to do the update this weekend
