### ISSUE TITLE
Scenario Syntax Error after Comment in Rider 2023.3

### ISSUE THREAD

**Issue by DerAlbertCom** [SpecFlowOSS/SpecFlow.Rider#207]
Minimal Reproduction:

```gherkin
Feature: Dummy
	Simple calculator for adding two numbers

#
Scenario: Scenario 1
	Given you are on the details page of an existing customer

#
Scenario: Scenario 2
	Given you are on the details page of an existing customer
```

With Rider 2023.3 RC1 and PlugIn Version 1.23.1 I get the following Error

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/136992/a6e0c823-c434-4e32-9494-aa38dea45d9e)

Remove then # from the Scenario 2 will remove the Syntax Error.

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/136992/d374194c-e187-4b1e-8506-79e455d1f594)

Will not happen on the first scenario. Setting a # in front of Given in the first scenario before will remove the Error.

A colleague with PlugIn 1.17.0 and an 2023.2 Version of Rider does not have this warning.

Invalidation of Caches from Rider and restarting did not help.

**Comment by Socolin** [comment]
Yes, it was a bug with 1.22 through 1.23.2
