### ISSUE TITLE
Run buttons are invisible in feature files

### ISSUE THREAD

**Issue by dmitryzarubin** [SpecFlowOSS/SpecFlow.Rider#209]
After the update of Rider and SpecFlow plugin, the "run" buttons disappeared

<img width="700" alt="image" src="https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/31827085/a336e500-b0e9-4feb-8a9f-523796db02f5">

Workaround 
It's still possible to run a scenario from Unit Test Explorer

JetBrains Rider 2023.3.1
Build #RD-233.11799.303, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2
.NET Core v7.0.10 x64 (Server GC)

SpecFlow for Rider
1.23.4

**Comment by Socolin** [comment]
Hello,

What it the path of the .feature file and what is the namespace in the .feature.cs ?

**Comment by JKetelaar** [comment]
Same issue here.

Path of the feature file:
<img width="430" alt="image" src="https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/3681904/08a86b82-0d54-4213-bae0-1bdc1ac53c84">

Namespace of the `.feature.cs` files:
```
namespace AOP.Specs.Features
```

**Comment by t-strecker** [comment]
Hello, I have same issue here.

**Comment by Socolin** [comment]
Can you try with latest version ? 1.23.6
https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/7257896631

If the problem persist, I will need the **full** path of the file relative to the solution file with the solution folder and the namespace / class name in the feature.cs or a repro.

**Comment by JKetelaar** [comment]
> Can you try with latest version ? 1.23.6 https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/7257896631
> 
> If the problem persist, I will need the **full** path of the file relative to the solution file with the solution folder and the namespace / class name in the feature.cs or a repro.

Awesome, that seems to have fixed it for me! Thank you!

**Comment by dmitryzarubin** [comment]
@Socolin , thank you! The issue has been fixed in the last version.
