### ISSUE TITLE
'Run' guttermarks not displayed for test inside non-ASCII folders

### ISSUE THREAD

**Issue by EnakiU** [SpecFlowOSS/SpecFlow.Rider#217]
STR:
1. Create a new folder with the name 'NotAsciiÆØÅ'
2. Copy tests from any other place to this folder
3. Rebuild solution
**Result:** tests discovered and displayed in Test Explorer, but there are no guttermarks next to tests in the editor.
![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/71037521/7da9d8a2-74db-445a-8163-0bfea4b657f2)

https://youtrack.jetbrains.com/issue/RIDER-106947

**Comment by Socolin** [comment]
I will no longer maintain this project since I cannot publish any new update for this plugin, see #214 for more details.
Please re-open the issue here https://github.com/reqnroll/Reqnroll.Rider if this is still relevant
