### ISSUE TITLE
Step files seems not to be recognized if generated with SourceGenerators

### ISSUE THREAD

**Issue by rafalmaciag** [SpecFlowOSS/SpecFlow.Rider#218]
Given a step file is generated in a separate dll (that uses source-generators to generate StepFiles), that is references using "specflow.json", the auto-completion seems not to recognize StepFiles.

Test runner, works fine, all steps are recognized when running tests.

**Comment by Socolin** [comment]
I will no longer maintain this project since I cannot publish any new update for this plugin, see #214 for more details.
Please re-open the issue here https://github.com/reqnroll/Reqnroll.Rider if this is still relevant
