### ISSUE TITLE
Specflow plugin causes JSON analysis error in Rider 2024.1

### ISSUE THREAD

**Issue by leandrohpa** [SpecFlowOSS/SpecFlow.Rider#220]
Hi,

After upgrading to Rider 2024.1, all the json files have highlighted errors by default.

The inspection finds an error: "The file does not contain a Feature."

Rider support helped me find that the issue was on the Specflow plugin after opening an issue to them. In the end, disabling it solves the issue, but it might be quite annoying for people working with Specflow and willing to use the plugin.
https://youtrack.jetbrains.com/issue/RIDER-110824/Incorrect-error-inspection-in-JSON-files-The-file-does-not-contain-a-Feature.

This happens in any JSON I've tested using C#-based projects (ClassLibrary, Console and Web)

This was a new test project I created from scratch using the C# Web Application template and this is the generated appsettings.json

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/81882708/184c608d-02cf-41bd-874c-ded66c0083b2)

**Comment by mcallaghan-geotab** [comment]
dup of https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/211 I think

**Comment by Socolin** [comment]
Please uninstall Specflow plugin THEN install reqnroll plugin for 2024.1 https://plugins.jetbrains.com/plugin/24012-reqnroll-for-rider, see details in #214
