### ISSUE TITLE
Code navigation fails with int wrapped with generic parameter

### ISSUE THREAD

**Issue by LouisSimon73** [SpecFlowOSS/SpecFlow.Rider#24]
Hello team,

New code navigation in Rider is supper nice !
We have a small bug here.

If I define:
[When("I have this integer (\d+)")] 

Then use it like that in a scenario outline:
When I have this integer <myInteger>
| myInteger |
|             10 |

**=> The step cannot be found and I have an error.**

Thank you for your work !

**Comment by Socolin** [comment]
In this case, we try to match `<integer>` with `\d+` that is not working.

I'm not sure about the solution, should we try to replace `<>` with like the first example in `Examples` to check this properly ?

**Comment by LouisSimon73** [comment]
Yes, I am sorry, this is a scenario outline so it should be like that :

Scenario outline:
      When I have this <integer>
     
Examples:
      | myInteger |
      |             10 |

**Comment by nemesv** [comment]
@Socolin using the first example would be the best solution. 

So when building the `SpecflowStepsUsagesCache` we should replace the outline parameters (using the first example) in the stepText before creating the `SpecflowStepUsageCacheEntry`

**Comment by LouisSimon73** [comment]
I do not follow you but I have to say that the test is working fine and that it was woring for a long time already.
This is just a problem of static analysis. Runtime is fine.

**Comment by nemesv** [comment]
@LouisSimon73  yes this issue is only in the Rider analysis part, it has no effect on discovering or running the tests.

**Comment by LouisSimon73** [comment]
I also did not mention that is is working fine with (.*) for some other tests that do not require the integer/string distinction

**Comment by Socolin** [comment]
This should be fixed in `master`
@LouisSimon73 if you want to test this without waiting we release a new version, you can the latest build here https://github.com/SpecFlowOSS/SpecFlow.Rider/actions
