### ISSUE TITLE
* not recognized as a replacement for Given/Then/When keyword

### ISSUE THREAD

**Issue by molszews** [SpecFlowOSS/SpecFlow.Rider#25]
Given spec
```
Scenario: Card purchase

Given a user is signed in
And the user has a registered payment method
* card type is VISA from DE
* strong customer authentication is active
And the user makes an order
* requested delivery of 15 November
* package weight 0.5 kg and declared value 100 EUR
```

Lines starting with `*` will remain marked as `Unresolved step`
Changing `*` to `And` works as a workaround

**Comment by Socolin** [comment]
Does `*` should be consider as `And` or is it more complex ?

Currently it's being interpreted as another step kind since the `*` can be found in all step kind in the `i18n.json`

If it's just an `And` it can be handled at the top of  `GherkinStepKind GetStepKind(string language, string keyword)`

**Comment by nemesv** [comment]
The `*` should be treated as `And/But` so we can handle it in the `GetStepKind`.

**Comment by Socolin** [comment]
This should be fixed in `master`
