### ISSUE TITLE
Steps using the But keyword are marked as Unresolved step

### ISSUE THREAD

**Issue by nemesv** [SpecFlowOSS/SpecFlow.Rider#26]
Example scenario:

```
Scenario Outline: Add two numbers
	Given the first number is 15
	But the second number is 70
	When the two numbers are added
	Then the result should be 120
```

The step "the second number is 70" is marked as unresolved.

![image](https://user-images.githubusercontent.com/251330/109491319-b58da800-7a89-11eb-8147-8e4eb85c952f.png)

However the step is recognized when using **And**

![image](https://user-images.githubusercontent.com/251330/109491374-c76f4b00-7a89-11eb-83f5-5ad0a4918729.png)

The **But** should work as the **And** keyword.

**Comment by Socolin** [comment]
I think we can just add `case "But":` in the GetStepKind

**Comment by Socolin** [comment]
This should be fixed in `master`
