### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Socolin** [SpecFlowOSS/SpecFlow.Rider#29]
Since tests do not run on linux (Jetbrains is workin on this) I was not able to maintain this.

I think we should setup build server using a Windows agent and run the tests on this after fixing them.

**Comment by nemesv** [comment]
The tests are currently also not running on window (they are failing with various reasons), we are currently looking into this. 

When they are finally green, running them in a Github action/Azure Devops build would be a good idea.

**Comment by Socolin** [comment]
Tests are fixed and running on build server now
