### ISSUE TITLE
Extend Gherkin Syntax Highlighting

### ISSUE THREAD

**Issue by mariostnr** [SpecFlowOSS/SpecFlow.Rider#30]
In order to offer a great writing experience for Gherkin feature files and scenarios
for Developers and Testers
the Rider plugin will support the "official" Gherkin Syntax Highlighting (Gherkin v6)

Acceptance criteria:

- Arguments should be identified by patterns (numbers, quoted strings e.g. "+ " or ' + ') -> needs to be implemented
- The behavior of the Syntax Highlighting should be documented in form of Gherkin feature files

**Comment by nemesv** [comment]
This will be released in the next version.

**Comment by nemesv** [comment]
Included in 1.3.7
