### ISSUE TITLE
Document current state of the plugin

### ISSUE THREAD

**Issue by mariostnr** [SpecFlowOSS/SpecFlow.Rider#34]
In order to help users when searching for help or decide to contribute to the open-source development
we want to document the current state/feature set of the Rider plugin

GitHub:
* https://github.com/SpecFlowOSS/resharper-specflow

Acceptance criteria:

* Rider plugin should be an own sub-section in https://docs.specflow.org/projects/specflow/en/latest/
* the current feature set of the Rider plugin should be explained
* it should be explained how to contribute to the open-source development of the IDE
* should include a first, simplified "Getting Started" guide

**Comment by alimogithub** [comment]
Plugin docs:  https://docs.specflow.org/projects/specflow/en/latest/Rider/rider-installation.html

How to contribute:  https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/master/CONTRIBUTING.md

**Comment by mariostnr** [comment]
Here you can find the latest plugin docs: https://docs.specflow.org/projects/specflow/en/latest/Rider/rider-features.html
