### ISSUE TITLE
No SpecFlow Files in Conext Menu while adding new File

### ISSUE THREAD

**Issue by dhd80** [SpecFlowOSS/SpecFlow.Rider#42]
Hello, I can't see the SpecFlow Files in Rider, my workaround is to choose "File" from Context Menu (see attachment) and manually type xyz.feature 
~ Thanks in advance.
<img width="414" alt="Bildschirmfoto 2021-03-08 um 09 18 00" src="https://user-images.githubusercontent.com/28508999/110293731-37805280-7fef-11eb-8812-8dddce47a385.png">

**Comment by nemesv** [comment]
Thanks for the feedback! 
We are planning to add SpecFlow specific file types (Feature, Bindings, Hooks, etc) and also project templates similar to the Visual Studio extension.
