### ISSUE TITLE
Implement usage analytics

### ISSUE THREAD

**Issue by mariostnr** [SpecFlowOSS/SpecFlow.Rider#43]
In order to provide efficient support/maintenance and enhance the plugin based on actual usage
we want to measure anonymous usage behavior and add Application Insights events to the Rider plugin

Acceptance criteria:

Analytics should help us to answer the following questions:
* How often is the plugin installed?
* How often is the plugin loaded?
* How many people compile a SpecFlow project with the plugin?
* How many people run SpecFlow tests with the plugin?
* How many active users are using the plugin?

it should be able to disable tracking events with setting an environment variable
* Define an environment variable called SPECFLOW_TELEMETRY_ENABLED and set its value to 0. This disables all analytics, i.e. those collected by both the extension and SpecFlow itself (see “SpecFlow” and “SpecFlow Visual Studio Extension” in the privacy policy for details)
* https://docs.specflow.org/projects/specflow/en/latest/Misc/Usage-Analytics.html

**Comment by nemesv** [comment]
Included in 1.3.7
