### ISSUE TITLE
After pressing "Enter", the cursor should not be at the beginning of the new line 

### ISSUE THREAD

**Issue by alexandrafung** [SpecFlowOSS/SpecFlow.Rider#51]
**Current behaviour:**

![cursor](https://user-images.githubusercontent.com/8384757/111499300-16cca100-8743-11eb-8202-daef3263eb68.gif)

**Expected:**
The cursor in the new line should be aligned with the beginning of the previous row.

![image](https://user-images.githubusercontent.com/8384757/111499360-29df7100-8743-11eb-9c8f-b637377f3d3f.png)

**Comment by Socolin** [comment]
This should be fixed in https://github.com/SpecFlowOSS/SpecFlow.Rider/pull/54

**Comment by nemesv** [comment]
Fixed in version 1.4.0
