### ISSUE TITLE
Change icon near failed steps branch:  failed-step-gutter-icon

### ISSUE THREAD

**Issue by mariostnr** [SpecFlowOSS/SpecFlow.Rider#80]
In order to use a more appropriate icon for highlighting failed steps
we will replace the current icon near failed steps branch:  failed-step-gutter-icon

current behavior:

we could use different icons depending on the problem (I would keep the same base icon and like small variation, in that case, to avoid having a Christmas tree). Since 2021.1 icons do not require anymore complex conversion to c#, just a .svg

if multiple steps have a problem they will all get an icon:

![image](https://user-images.githubusercontent.com/16210566/115040324-9a5be800-9ed1-11eb-9294-acde87aa2994.png)

whereas if the step output something (like Console.WriteLine) the output will be shown in the popup:

![image](https://user-images.githubusercontent.com/16210566/115040448-bf505b00-9ed1-11eb-9b1f-65ca6aee2c61.png)

next step: we need to define some suitable icons

**Comment by nemesv** [comment]
Fixed in version 1.7.0
