### ISSUE TITLE
Add support for method name - underscores

### ISSUE THREAD

**Issue by LukasCornille** [SpecFlowOSS/SpecFlow.Rider#85]
Hi,

I'm currently working on a project where fellow devs are working with VS Studio and Rider.
We've come to an agreement to write our Specflow tests with underscores and parameters capitalised as possible on the [documentation](https://docs.specflow.org/projects/specflow/en/latest/Bindings/Step-Definitions.html).

I've added an example in the screenshot down bellow!
![image](https://user-images.githubusercontent.com/36887321/116413350-d24f1d80-a837-11eb-8b4c-64e25d797018.png)

However Rider analyses this way of working as errors. Could support be added for this?

**Comment by Socolin** [comment]
This should be fixed in the next version
https://github.com/SpecFlowOSS/SpecFlow.Rider/commit/ec7efc0ac5424a4fa1d5ba9e9d12ecfbd5888c2b

**Comment by nemesv** [comment]
Fixed in version 1.7.0
