### ISSUE TITLE
Typing assist doesn't work

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#87]
Preconditions: table provided
```
    Examples:
      | stars | rating |
      | 1     | Poor   |
      | 2     | Rich   |
```

STR:
1. Type the next row

ACTUAL: The table is not formatted on the fly. Indentations are incorrectly formatted.
![image](https://user-images.githubusercontent.com/48007045/116976506-eb3d5000-acc9-11eb-9a30-e366c1e57ceb.png)

**Comment by Socolin** [comment]
It should be fixed with https://github.com/SpecFlowOSS/SpecFlow.Rider/pull/109

**Comment by tkapustina** [comment]
![specflowindent](https://user-images.githubusercontent.com/48007045/121058579-27803680-c7c9-11eb-92b5-a1709cd5c8a8.gif)
- wrong caret position when hitting enter
- table content is not aligned with the header
