### ISSUE TITLE
Wrong spacing on "Where to create the step?" UI

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#88]
**STR:**
Preconditions: No binded cs files

STR:
1. Type a new scenario
2. Invoke quick fix to create a step

ACTUAL:
? is written after the space
"Nothing to show" is aligned to the bottom
![image](https://user-images.githubusercontent.com/48007045/116976684-28094700-acca-11eb-9290-07f25d4435f1.png)

**Comment by nemesv** [comment]
We are using the built in `JetPopupMenus` control of Rider for the popup which automatically includes the "Nothing to show" message when there are no items, so we might not able to change the indentation.  @Socolin what do you think?

**Comment by Socolin** [comment]
This should be fixed with https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/22

**Comment by nemesv** [comment]
Fixed in version 1.8.0.

**Comment by tkapustina** [comment]
New implementation:
If there are no bindings
![image](https://user-images.githubusercontent.com/48007045/125955667-02293575-3d31-4da0-ac3c-31358bb2fdcd.png)
If there are some 
![image](https://user-images.githubusercontent.com/48007045/125955730-375786a9-8aa1-4b7b-b96c-ebe9ea349ebf.png)

Verified.
