### ISSUE TITLE
"Where to create the step?" UI isn't consistent

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#89]
**STR:**
Preconditions: There are binded cs files

STR:
1. Invoke create a step quick fix

EXPECTED: Is it possible to make them consistent?
feature files
![image](https://user-images.githubusercontent.com/48007045/116979194-59cfdd00-accd-11eb-84a2-c4ec51a57977.png)

cs files
![image](https://user-images.githubusercontent.com/48007045/116977887-a2869680-accb-11eb-9ebf-fd6ef4187fcc.png)

**Comment by Socolin** [comment]
I think this one was fixed can you confirm this ?

**Comment by tkapustina** [comment]
@Socolin here is what I see in 1.7.0
![image](https://user-images.githubusercontent.com/48007045/121653771-b7620100-caa5-11eb-85db-c6525bb131c8.png)
Is that what you want me to test?

**Comment by Socolin** [comment]
I think the problem was that the list of classes was not ordered

**Comment by tkapustina** [comment]
Verified that the list is ordered alphabetically. 
The namespace ui presentation differs from the cs editor.
Written next to the class name, the font is black.
![image](https://user-images.githubusercontent.com/48007045/127182540-c626d1ec-bd74-46b5-b9d8-8498325a9ae3.png)
Written in braces, the font is gray.
![image](https://user-images.githubusercontent.com/48007045/127182710-6aaf3354-26d0-4835-9eae-f265a8bce6e3.png)

**Comment by nemesv** [comment]
It is fixed in version 1.9.3

**Comment by radu-ieso** [comment]
should this be closed?

**Comment by SabotageAndi** [comment]
Jup
