### ISSUE TITLE
Decrease default severity of unresolved steps

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#90]
If I write a scenario from scratch, everything will be highlighted as an error. Error severity shows that there are critical errors in the code and looks aggressively
![image](https://user-images.githubusercontent.com/48007045/116980401-dd3dfe00-acce-11eb-8455-6defda5ddd18.png)

**Comment by tkapustina** [comment]
The bulb should be yellow in accordance with the highlighting 
![image](https://user-images.githubusercontent.com/48007045/121006214-4ebf0f80-c799-11eb-8aec-abf7e769810b.png)

**Comment by nemesv** [comment]
Fixed in version 1.8.0.

**Comment by tkapustina** [comment]
verified
