### ISSUE TITLE
Generate step produces unresolved code

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#92]
STR:
1. Create a step

ACTUAL:
![image](https://user-images.githubusercontent.com/48007045/116982652-bb924600-acd1-11eb-8f71-7106105a52e2.png)

**Comment by nemesv** [comment]
Currently we cannot reproduce this issue.
Is this a code analysis error or the project does not compile?
Was this an existing project or a newly created one with the template? 
Could you please include the SpecFlow and test runner versions?

**Comment by tkapustina** [comment]
- Open https://github.com/SteveSanderson/GuestbookDemo/blob/master/Guestbook.Spec/Features/Posting.feature 
- Add a step and generate the method

**Comment by nemesv** [comment]
This project uses a very old version of SpecFlow 1.2 which does not yet have this method `StepIsPending`

We only officially support a latest version of SpecFlow: https://specflow.org/support/

For up to date example projects you could check out this repository:
https://github.com/SpecFlowOSS/SpecFlow-Examples/tree/master/BowlingKata

We could think about adding later some extra warning if the project has an unsupported/old SpecFlow version.
