### ISSUE TITLE
Add run tests action in the feature file context menu

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#94]
Please, add run tests action to this menu as it's available for unit tests.
![image](https://user-images.githubusercontent.com/48007045/116983432-c1d4f200-acd2-11eb-910c-f7e9f665b837.png)

**Comment by Socolin** [comment]
I will need to confirm this but I think this is automatically enabled with the TestExplorer
This may be linked to https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/37

**Comment by Socolin** [comment]
Some information are available here

https://jetbrains.slack.com/archives/CBZ36NH7C/p1620701055171500

**Comment by tkapustina** [comment]
Verified. Added on the project and the file levels.
I'm not sure if we need to have the action for feature.cs but imho it might be left as it is.
