### ISSUE TITLE
The gutter mark doesn't appear

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#96]
STR:
net48
![image](https://user-images.githubusercontent.com/48007045/116986144-19289180-acd6-11eb-87cb-d0a0b54ada09.png)

Am I missing something? Rebuild doesn't help.

**Comment by tkapustina** [comment]
I don't have the gutter mark at all for net5, xunit. SpecFlow.xUnit referenced. 
![image](https://user-images.githubusercontent.com/48007045/117034688-3d9f6080-ad0c-11eb-9c95-8f08535a5cf6.png)

**Comment by tkapustina** [comment]
https://youtrack.jetbrains.com/issue/RIDER-61108 seems to be related

**Comment by Socolin** [comment]
Hello,

Do you see the tests in the Unit test window ? They should appear only after building when the `.feature.cs` is generated.
Can you share the project so we can reproduce this issue ?

**Comment by tkapustina** [comment]
STR1: Unload and reload any project
![image](https://user-images.githubusercontent.com/48007045/117108153-76324f00-ad8b-11eb-9620-b55882bd20c8.png)


STR2: https://github.com/SabotageAndi/SpecFlow.Example.AllTestRunners/tree/master/XUnit2
![image](https://user-images.githubusercontent.com/48007045/117108104-5e5acb00-ad8b-11eb-9763-bfefd52d4041.png)

STR3:
1. https://github.com/SteveSanderson/GuestbookDemo/blob/master/Guestbook.Spec/Features/Posting.feature
2. Add a scenario
```
    Scenario: Viewing the newest posting page
        Given I am on the newest posting page
        Then I should see a field labelled "Your name"
        And I should see a field labelled "Your comment"
```
3. Generate the given
4. Rebuild

ACTUAL: The test doesn't appear in unit tests, .feature.cs isn't regenerated


[Posting.feature.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/6425537/Posting.feature.zip)

**Comment by Socolin** [comment]
This is an old project using Specflow 1.2 and Nunit 2.5.3
I'm unable to debug this on Linux, I don't know if we want to support those old versions.

```
    <Reference Include="nunit.framework, Version=2.5.3.9345, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\NUnit 2.5.3\bin\net-2.0\framework\nunit.framework.dll</HintPath>
    </Reference>
    <Reference Include="TechTalk.SpecFlow, Version=1.2.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>External Assemblies\TechTalk.SpecFlow.dll</HintPath>
    </Reference>
```

**Comment by nemesv** [comment]
We don't support old SpecFlow versions: https://specflow.org/support/ 
We can think about to add some warnings/notifications when the project uses some old/unsupported SpecFlow version

I will try to reproduce this on Windows with the latest SpecFlow.

**Comment by tkapustina** [comment]
There is no the gutter mark for net48 either. And btw is it expected that .feature.cs is not included in the project?
![image](https://user-images.githubusercontent.com/48007045/117322775-fa252d80-ae96-11eb-8dd5-f0fcd0ef56c0.png)
Net48, SpecFlow.NUnit3.7.38, NUnit 3.13.2

**Comment by Socolin** [comment]
@tkapustina Could you share the project in the last screenshot ?

**Comment by tkapustina** [comment]
attached
[TestProject5.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/6522838/TestProject5.zip)

**Comment by tkapustina** [comment]
verified
