### ISSUE TITLE
.feature.cs is not nested after creation

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#99]
Preconditions: net5, xunit, feature file with steps, steps created, no .feature.cs

STR:
1. Build the project so .feature.cs will be available

ACTUAL: .feature.cs is not nested. Reload fixes the issue.
![image](https://user-images.githubusercontent.com/48007045/117032933-9a018080-ad0a-11eb-891c-541cc3f12788.png)

**Comment by tkapustina** [comment]
Should it be fixed in 1.7.0?

**Comment by nemesv** [comment]
Yes, this should be in 1.7.0. If I now create a new  net5, xunit specflow project after the rebuild the feature.cs file is nested correctly.

**Comment by tkapustina** [comment]
Verified.
Note that feature.cs is not included in the project model in classic apps, unrelated to Rider.
Another interesting point about classic apps is that file templates added via Rider are not included in the project models in VS2019. It looks like we don't need to fix this difference as the building passes successfully.
